package com.paybille.invoicer.core.designsystem.theme

// Generado por documentacion/scripts/material_symbols.py (codepoints del cmap de la fuente).
// Para añadir uno a mano: material-symbols-rounded.codepoints, junto al script.

/** Icono de Material Symbols Rounded: el codepoint de su glifo en `material_symbols_rounded.ttf`. */
@kotlin.jvm.JvmInline
value class PbSymbol(val codepoint: Int)

/** Los iconos que usa la app, por su nombre en fonts.google.com/icons. */
object PbSymbols {
    /** `account_balance` */ val AccountBalance = PbSymbol(0xE84F)
    /** `account_balance_wallet` */ val AccountBalanceWallet = PbSymbol(0xE850)
    /** `account_circle` */ val AccountCircle = PbSymbol(0xE853)
    /** `add` */ val Add = PbSymbol(0xE145)
    /** `add_a_photo` */ val AddAPhoto = PbSymbol(0xE439)
    /** `add_box` */ val AddBox = PbSymbol(0xE146)
    /** `add_card` */ val AddCard = PbSymbol(0xEB86)
    /** `arrow_back` */ val ArrowBack = PbSymbol(0xE5C4)
    /** `arrow_downward` */ val ArrowDownward = PbSymbol(0xE5DB)
    /** `arrow_upward` */ val ArrowUpward = PbSymbol(0xE5D8)
    /** `badge` */ val Badge = PbSymbol(0xEA67)
    /** `bar_chart` */ val BarChart = PbSymbol(0xE26B)
    /** `barcode` */ val Barcode = PbSymbol(0xE70B)
    /** `calendar_month` */ val CalendarMonth = PbSymbol(0xEBCC)
    /** `call` */ val Call = PbSymbol(0xE0B0)
    /** `category` */ val Category = PbSymbol(0xE574)
    /** `check` */ val Check = PbSymbol(0xE5CA)
    /** `check_circle` */ val CheckCircle = PbSymbol(0xE86C)
    /** `chevron_right` */ val ChevronRight = PbSymbol(0xE409)
    /** `close` */ val Close = PbSymbol(0xE14C)
    /** `cloud_off` */ val CloudOff = PbSymbol(0xE2C1)
    /** `cloud_upload` */ val CloudUpload = PbSymbol(0xE2C3)
    /** `content_copy` */ val ContentCopy = PbSymbol(0xE14D)
    /** `credit_card` */ val CreditCard = PbSymbol(0xE870)
    /** `currency_exchange` */ val CurrencyExchange = PbSymbol(0xEB70)
    /** `delete` */ val Delete = PbSymbol(0xE872)
    /** `description` */ val Description = PbSymbol(0xE873)
    /** `download` */ val Download = PbSymbol(0xE171)
    /** `edit` */ val Edit = PbSymbol(0xE150)
    /** `error` */ val Error = PbSymbol(0xE000)
    /** `event` */ val Event = PbSymbol(0xE24F)
    /** `expand_less` */ val ExpandLess = PbSymbol(0xE5CE)
    /** `expand_more` */ val ExpandMore = PbSymbol(0xE5CF)
    /** `group` */ val Group = PbSymbol(0xE7EF)
    /** `hide_image` */ val HideImage = PbSymbol(0xF022)
    /** `history` */ val History = PbSymbol(0xE28E)
    /** `home` */ val Home = PbSymbol(0xE88A)
    /** `image` */ val Image = PbSymbol(0xE251)
    /** `inbox` */ val Inbox = PbSymbol(0xE156)
    /** `info` */ val Info = PbSymbol(0xE88E)
    /** `inventory_2` */ val Inventory2 = PbSymbol(0xE1A1)
    /** `link` */ val Link = PbSymbol(0xE157)
    /** `lock` */ val Lock = PbSymbol(0xE88D)
    /** `logout` */ val Logout = PbSymbol(0xE9BA)
    /** `mail` */ val Mail = PbSymbol(0xE0BE)
    /** `monitoring` */ val Monitoring = PbSymbol(0xF190)
    /** `more_horiz` */ val MoreHoriz = PbSymbol(0xE5D3)
    /** `notifications` */ val Notifications = PbSymbol(0xE7F4)
    /** `notifications_active` */ val NotificationsActive = PbSymbol(0xE7F7)
    /** `open_in_new` */ val OpenInNew = PbSymbol(0xE895)
    /** `palette` */ val Palette = PbSymbol(0xE3B7)
    /** `payments` */ val Payments = PbSymbol(0xEF63)
    /** `percent` */ val Percent = PbSymbol(0xEB58)
    /** `person` */ val Person = PbSymbol(0xE7FD)
    /** `person_add` */ val PersonAdd = PbSymbol(0xE7FE)
    /** `photo_camera` */ val PhotoCamera = PbSymbol(0xE3B0)
    /** `photo_library` */ val PhotoLibrary = PbSymbol(0xE413)
    /** `picture_as_pdf` */ val PictureAsPdf = PbSymbol(0xE415)
    /** `pin_drop` */ val PinDrop = PbSymbol(0xE55E)
    /** `qr_code_scanner` */ val QrCodeScanner = PbSymbol(0xF206)
    /** `receipt_long` */ val ReceiptLong = PbSymbol(0xEF6E)
    /** `remove` */ val Remove = PbSymbol(0xE15B)
    /** `request_quote` */ val RequestQuote = PbSymbol(0xF1B6)
    /** `savings` */ val Savings = PbSymbol(0xE2EB)
    /** `schedule` */ val Schedule = PbSymbol(0xE192)
    /** `search` */ val Search = PbSymbol(0xE8B6)
    /** `sell` */ val Sell = PbSymbol(0xE54E)
    /** `settings` */ val Settings = PbSymbol(0xE8B8)
    /** `share` */ val Share = PbSymbol(0xE80D)
    /** `storefront` */ val Storefront = PbSymbol(0xEA12)
    /** `swap_vert` */ val SwapVert = PbSymbol(0xE0C3)
    /** `sync` */ val Sync = PbSymbol(0xE627)
    /** `trending_down` */ val TrendingDown = PbSymbol(0xE8E3)
    /** `trending_up` */ val TrendingUp = PbSymbol(0xE8E5)
    /** `visibility` */ val Visibility = PbSymbol(0xE417)
    /** `visibility_off` */ val VisibilityOff = PbSymbol(0xE8F5)
    /** `warning` */ val Warning = PbSymbol(0xE002)
}
